### ISSUE TITLE
Add support for Ribbon titles

### ISSUE THREAD

**Issue by Azekthi** [Azekthi/RibbonMasters#7]
- [x] Add titles to internal data
- [x] Add title selection and storage
- [x] Display title ~~next to nickname~~ below nickname similar to mints

**Comment by SadisticMystic** [comment]
I would suggest the title be displayed similar to how mints currently are.

**Comment by Azekthi** [comment]
I was just going to have the title simply appear as part of the name. I didn't even think about replicating the mint layout, that's a much better idea! I could even have the associated Ribbon/Mark show as an icon like the mints do.

The funny thing is, I didn't even come up with the nature and mint layout, that's a recreation of how HOME shows it in the GTS. I would love if they added titles to HOME in a similar way.
